name: SpeedrunnerSwap
version: '${project.version}'
main: com.example.speedrunnerswap.SpeedrunnerSwap
api-version: '1.20'
authors: [YourName]
description: Dream-style "Speedrunner Swap" challenge where speedrunners share the same state and swap control on a timer
website: https://github.com/yourusername/speedrunnerswap

commands:
  swap:
    description: Main command for SpeedrunnerSwap plugin
    usage: /<command> [start|stop|pause|resume|status|setrunners|sethunters|reload|gui]
    permission: speedrunnerswap.command
    
permissions:
  speedrunnerswap.command:
    description: Allows use of all SpeedrunnerSwap commands
    default: op
  speedrunnerswap.admin:
    description: Allows administration of SpeedrunnerSwap
    default: op
    children:
      speedrunnerswap.command: true