# SpeedrunnerSwap Configuration
# Version 3.0.0

# General Game Rules
# A list of worlds where the game is allowed to be started and played.
# If the list is empty, all worlds are allowed.
allowed-worlds:
  - "world"
  - "world_nether"
  - "world_the_end"

# Teams Configuration
teams:
  runners: []  # List of runner player names
  hunters: []  # List of hunter player names

# Swap System Configuration
swap:
  # Fixed interval or random swap with Gaussian jitter
  randomize: true
  # Base interval in seconds (or mean if randomized)
  interval: 60
  # Min and max interval in seconds (only used if randomize is true)
  min_interval: 30
  max_interval: 90
  # Jitter settings (only used if randomize is true)
  jitter:
    # Standard deviation in seconds
    stddev: 15
    # Whether to clamp within min/max limits
    clamp: true
  # Grace period after swaps (in ticks, 20 ticks = 1 second)
  grace_period_ticks: 40
  # Auto-pause if a runner disconnects
  pause_on_disconnect: true

# Safe Swap Configuration
safe_swap:
  # Whether to enable safe swap feature
  enabled: true
  # Horizontal scan radius (blocks)
  horizontal_radius: 5
  # Vertical scan distance (blocks)
  vertical_distance: 10
  # Dangerous blocks to avoid (material names)
  dangerous_blocks:
    - LAVA
    - MAGMA_BLOCK
    - CACTUS
    - CAMPFIRE
    - FIRE
    - SOUL_FIRE
    - SOUL_CAMPFIRE
    - POINTED_DRIPSTONE

# Freeze Mode for Inactive Runners
# Options: EFFECTS, SPECTATOR
freeze_mode: EFFECTS

# Movement and Interaction Control
cancel:
  # Cancel movement for inactive runners
  movement: true
  # Cancel interactions for inactive runners
  interactions: true

# Hunter Tracker Configuration
tracker:
  # How often to update the tracker (in ticks, 20 ticks = 1 second)
  update_ticks: 20
  # Modes can be a combination of: COMPASS, GLOWING, ACTION_BAR
  modes:
    - COMPASS
    - ACTION_BAR
  # If true, the compass will only point to the runner if the hunter is in the same world.
  compass-requires-same-world: true

# GUI Configuration
gui:
  main_menu:
    title: "SpeedrunnerSwap Menu"
    rows: 3
  team_selector:
    title: "Team Selector"
    rows: 4
  settings:
    title: "Settings"
    rows: 5

# Broadcast Configuration
broadcasts:
  # Whether to broadcast swap events to all players
  enabled: true
  # Whether to broadcast game start/stop events
  game_events: true
  # Whether to broadcast team changes
  team_changes: true

# Simple Voice Chat Integration (if available)
voice_chat:
  # Whether to integrate with Simple Voice Chat
  enabled: true
  # Whether to mute inactive runners
  mute_inactive_runners: true

# Audio-Visual Effects Configuration
effects:
  swap-warning:
    enabled: true
    sound: "BLOCK_NOTE_BLOCK_PLING"
    volume: 1.0
    pitch: 1.5
    title: "&e&lSWAP IN 10 SECONDS"
    subtitle: ""
  swap-execute:
    enabled: true
    sound: "ENTITY_ENDERMAN_TELEPORT"
    volume: 1.0
    pitch: 1.0
    title: "&c&lSWAPPED!"
    subtitle: "&fTo %new_runner%"
  game-start:
    enabled: true
    sound: "ENTITY_PLAYER_LEVELUP"
    volume: 1.0
    pitch: 1.0
    title: "&a&lGAME STARTED"
    subtitle: "&eGood luck, runners!"
  game-end:
    enabled: true
    sound: "ENTITY_WITHER_DEATH"
    volume: 1.0
    pitch: 1.0
    title: "&c&lGAME OVER"
    subtitle: ""

# Chat & Communication Rules
chat-isolation:
  # If true, runners will not be able to see chat messages from each other.
  block-runner-chat: true
  # If true, runners will not be able to send private messages to each other (e.g. /msg, /tell).
  block-runner-pms: true
  # Message sent to a runner if they try to message another runner.
  message-block-reply: "&cYou cannot communicate with other runners during the game."