name: SpeedrunnerSwap
main: com.yourname.speedrunnerswap.SpeedrunnerSwap
version: 3.0.0
api-version: '1.20'
author: YourName
description: Dream-style Speedrunner Swap with a full feature set.
commands:
  swap:
    description: Control the Speedrunner Swap game
    usage: /swap <start|stop|pause|resume|status|reload|gui>
    permission: speedrunnerswap.admin
permissions:
  speedrunnerswap.admin:
    description: Allows using all /swap admin commands
    default: op